config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :cheets

  # Hey future Bailey! You are awesome. Remember, this is for the feed:
  get '/cheets' => 'cheets#index'
  get '/new' => 'cheets#new'

  root 'users#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cheet.rb
class Cheet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cheets_controller.rb
class CheetsController < ApplicationController

  def index
    @cheets = Cheet.all
  end

  def create
    @cheet = Cheet.new(params.require(:cheets).permit(:text))
    if @cheet.save
      redirect_to @cheet
    else
      render "new"
    end
  end

  def show
    @cheet = Cheet.find(params[:id])
  end

  def new
  end

  private
  def cheet_params
    params.require(:cheets).permit(:text)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(params.require(:users).permit(:name, :username, :email, :password))
    @user.save
    redirect_to @user
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cheets_helper.rb
module CheetsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cheets/index.html.erb
<h1>Feed</h1>

<table>
  <tr>
    <th>Text</th>
  </tr>

  <% @cheets.each do |cheet| %>
    <tr>
      <td><%= cheet.text %></td>
    </tr>
  <% end %>
</table>

app/views/cheets/new.html.erb
<h1>New Cheet</h1>

<%= form_for :cheets, url: cheets_path do |f| %>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/cheets/show.html.erb
<p>
  <strong>Cheet:</strong>
  <%= @cheet.text %>
</p>

app/views/homepage/index.html.erb
<h1>Welcome to Chitter</h1>
<p>This is a magical Twitter clone, built with Rails</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsChitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Welcome to Chitter</h1>
<p>This is a magical Twitter clone, built with Rails</p>

<%= form_for :users, url: users_path do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>

    <%= f.label :username %><br>
    <%= f.text_field :username %><br>

    <%= f.label :email %><br>
    <%= f.text_field :email %><br>

    <%= f.label :password %><br>
    <%= f.text_field :password %><br>
  </p>

  <p>
    <%= f.submit "Sign up" %>
  </p>
<% end %>

app/views/users/show.html.erb
<p>
  <strong>Hi!</strong>
  <%= @user.username %>
</p>